### ISSUE TITLE
Change contact list

### ISSUE THREAD

**Issue by chatainsim** [trmendes/BirthDayDroid-moving-to-gitlab#3]
Hello,
Can you add the ability to change contact list to use with BirthDayDroid ?

Thank you.

**Comment by trmendes** [comment]
Hi. What do you mean by that?

**Comment by chatainsim** [comment]
Mi account and Google account have some duplicated contact then BirthDayDroid display them both.
I need the ability to say to BirthDayDroid to only use Google contact for exemple and not all of them.

![img_20170302_141209](https://cloud.githubusercontent.com/assets/1167931/23508539/7dc82dc0-ff52-11e6-8688-be6657ef2a54.jpg)

**Comment by trmendes** [comment]
moving this project to gitlab
