### ISSUE TITLE
Bug? All entrys display wrong age

### ISSUE THREAD

**Issue by d4v3k** [trmendes/BirthDayDroid-moving-to-gitlab#8]
For some reason all entrys in my list are displayed with a wrong age for the coming birthday (actual age -1)

I hope this isn't intended 😅

Great app by the way.

**Comment by trmendes** [comment]
Fixed in the new version :O....waiting f-droid to compile it and publish.

Right now moving this project to gitlab :D...

Thanks for helping :)...if you have any ideas to the app or any other bug to report just open an issue in the gitlab repository :D
